# This file describes the firmwares that are built by the GitHub Actions CI.
# Supported hardware: https://zmk.dev/docs/hardware

include:

  ###
  # Composite Keyboards (external MCU)
  #
  # These keebs consist in two parts:
  #  - a shield = the keyboard itself
  #  - a board = the micro-controller unit (MCU), which can be:
  #
  #    - Pro Micro Interconnect:
  #      - nice!nano v2                 nice_nano@2//zmk
  #
  # => make sure the `board` field matches the MCU on your keyboard
  ##

  # Soflev2 + nice!nano v2
  - board: nice_nano@2//zmk
    shield: splitkb_aurora_sofle_left nice_view_adapter nice_view
    artifact-name: splitkb_aurora_sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2//zmk
    shield: splitkb_aurora_sofle_right nice_view_adapter nice_view
    artifact-name: splitkb_aurora_sofle_right
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
